apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kong1
  namespace: kong1
spec:
  releaseName: kong1
  chart:
    spec:
      chart: kong1
      sourceRef:
        kind: HelmRepository
        name: kong1
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    redis:
      enabled: true
      repository: public.ecr.aws/docker/library/redis
      tag: 7.0.6
    ingress:
      enabled: true
      className: nginx
